version: 2.1

jobs:
  simple:
    machine:
      image: 'windows-server-2022-gui:current'
    steps:
      - run:
          name: say something
          command: Write-Host 'Hello, Windows'

workflows:
  version: 2
  simple:
    jobs:
      - simple
