version: 2.1

jobs:
  simple:
    executor:
      name: win/default
    steps:
      - run:
          name: say something
          command: echo hello world!

workflows:
  version: 2
  simple:
    jobs:
      - simple
