version: 2.1

jobs:
  simple:
    macos:
      xcode: 13.3.0
    steps:
      - run:
          name: say something
          command: echo hello world!
      - run:
          name: save env vars
          command: echo "export CI_USER_PASSWORD=abc123" >> /Users/distiller/.bash_profile

workflows:
  version: 2
  simple:
    jobs:
      - simple
