version: 2.1

jobs:
  simple:
    macos:
      xcode: 13.3.0
    steps:
      - run:
          name: say something
          command: echo hello world

workflows:
  version: 2
  simple:
    jobs:
      - simple
